name: 'Container run'
description: 'Container action in the ECHR container'
inputs:
  cont_action:
    description: 'Container action'
    required: true
    default: 'help'
  action_params:
    description: 'Container action parameters'
    required: false
runs:
  using: 'docker'
  image: 'aquemy1/echr_build:develop'
  env:
    SRV_PARAMS: ${{ secrets.SRV_PARAMS }}
    ECHR_PASSWORD: ${{ secrets.ECHR_PASSWORD }}
  args:
    - ${{ inputs.cont_action }}
    - ${{ inputs.action_params }}
