name: 'Containertest  run'
description: 'Container action in the ECHR test container'
inputs:
  cont_action:
    description: 'Container action'
    required: true
    default: 'help'
  action_params:
    description: 'Container action parameters'
    required: false
runs:
  using: 'docker'
  image: 'echr-od/echr-od_process:develop'
  args:
    - ${{ inputs.cont_action }}
    - ${{ inputs.action_params }}
