name: 'Build test version'
description: 'Building test version of ECHR database'
inputs:
  cont_action:
    description: 'Container action'
    required: true
    default: 'help'
  action_params:
    description: 'Container action parameters'
    required: false
runs:
  using: 'docker'
  image: 'echr_build:develop'
  args:
    - ${{ inputs.cont_action }}
    - ${{ inputs.action_params }}
