name: Deployment

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Building image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF##*/})
      - name: Run linter
        uses: ./.github/actions/container_run
        with:
          container: 'echr-od/echr-od_process:develop'
          cont_action: 'lint'
      - name: Run unit tests
        uses: ./.github/actions/container_run
        with:
          container: 'echr-od/echr-od_process:develop'
          cont_action: 'test'
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aquemy1/echr_build
          tags: ${{ steps.branch_name.outputs.branch }}