name: 'Image Building'

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF##*/})
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aquemy1/echr_build:${{ steps.branch_name.outputs.branch }}
      - name: Run linter
        uses: ./.github/actions/container_run
        with:
          cont_action: 'lint'
      - name: Run unit tests
        uses: ./.github/actions/container_run
        with:
          cont_action: 'test'
      - name: Get coverage
        run: echo "COV=`cat cov_html/index.html | grep class=\"pc_cov\ | grep -oEi '\d*%'`" >> $GITHUB_ENV
      - name: Coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0a01112a76f73945a9f27710cf9c7a25
          filename: coverage.json
          label: Coverage
          message: ${{ env.COV }}
          color: green