name: 'Cyclic Release'

on:
  schedule:
    - cron: '0 0 1 * *'  # Every month
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Building image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: echr-od/ECHR-OD_process
          prefix: 'v'
        id: version
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: tag-${{ steps.version.outputs.tag }}
          RELEASE_NAME: monthly-release-${{ steps.date.outputs.date }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: aquemy1/echr_build:${{ steps.version.outputs.tag }}_${{ steps.date.outputs.date }}
      - name: Build test dataset
        uses: ./.github/actions/container_run
        with:
          cont_action: 'build'
          action_params: '--build ./build/test --workflow release'