name: Cyclic Release

on:
  schedule:
    - cron: '*/5 * * * *' # TEST every 15 minutes

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Building image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get the version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: tag-${{ steps.version.outputs.tag }}
          RELEASE_NAME: monthly-release-${{ steps.date.outputs.date }}
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aquemy1/echr_build
          tags: ${{ steps.version.outputs.tag }}_${{ steps.date.outputs.date }}