name: Test

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Building image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker images
        uses: docker/build-push-action@v1
        with:
          push: false
          tags: develop
      - name: Run linter
          uses: ./.github/actions/container_run
          with:
            container: 'echr-od/echr-od_process:develop'
            cont_action: 'lint'
      - name: Run unit tests
        uses: ./.github/actions/container_run
        with:
          container: 'echr-od/echr-od_process:develop'
          cont_action: 'test'
      - name: Build test dataset
        uses: ./.github/actions/container_run
        with:
          container: 'echr-od/echr-od_process:develop'
          cont_action: 'build'
          action_params: '--version test --build ./build/test'
